INSERT INTO klse_stocks (ticker_full, ticker_code, company_name, shariah_status, sector, market, is_active, is_top300, short_name, source_origin) VALUES ('0097.KL', '0097', 'VITROX CORPORATION BHD', 'SHARIAH', NULL, 'MYR', true, true, 'VITROX', 'migration_from_screener'),
('0166.KL', '0166', 'INARI AMERTRON BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'INARI', 'migration_from_screener'),
('03001.KL', '03001', 'CLOUDARON GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CLOUD', 'migration_from_screener'),
('0277.KL', '0277', 'CLOUDPOINT TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CLOUDPT', 'migration_from_screener'),
('0246.KL', '0246', 'CNERGENZ BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CNERGEN', 'migration_from_screener'),
('0149.KL', '0149', 'FIBON BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FIBON', 'migration_from_screener'),
('0101.KL', '0101', 'TMC LIFE SCIENCES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'TMCLIFE', 'migration_from_screener'),
('0165PA.KL', '0165PA', 'XOX BHD', 'SHARIAH', NULL, 'MYR', true, true, 'XOX-PA', 'migration_from_screener'),
('0229.KL', '0229', 'MOBILIA HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MOBILIA', 'migration_from_screener'),
('0156.KL', '0156', 'MANAGEPAY SYSTEMS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MPAY', 'migration_from_screener'),
('03019.KL', '03019', 'MATRIX PARKING SOLUTION HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MPSOL', 'migration_from_screener'),
('0008.KL', '0008', 'WILLOWGLEN MSC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'WILLOW', 'migration_from_screener'),
('0165.KL', '0165', 'XOX BHD', 'SHARIAH', NULL, 'MYR', true, true, 'XOX', 'migration_from_screener'),
('0055.KL', '0055', 'SERSOL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SERSOL', 'migration_from_screener'),
('0251.KL', '0251', 'SFP TECH HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SFPTECH', 'migration_from_screener'),
('03033.KL', '03033', 'SUPERGENICS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SGBHD', 'migration_from_screener'),
('0305.KL', '0305', 'SIN-KUNG LOGISTICS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SINKUNG', 'migration_from_screener'),
('03008.KL', '03008', 'SL INNOVATION CAPITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SLIC', 'migration_from_screener'),
('0215.KL', '0215', 'SOLARVEST HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SLVEST', 'migration_from_screener'),
('0132.KL', '0132', 'TECHNODEX BHD', 'SHARIAH', NULL, 'MYR', true, true, 'TDEX', 'migration_from_screener'),
('0242.KL', '0242', 'PAPPAJACK BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PPJACK', 'migration_from_screener'),
('0240.KL', '0240', 'CORAZA INTEGRATED TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CORAZA', 'migration_from_screener'),
('0261.KL', '0261', 'COSMOS TECHNOLOGY INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'COSMOS', 'migration_from_screener'),
('0150.KL', '0150', 'FINTEC GLOBAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FINTEC', 'migration_from_screener'),
('0150PA.KL', '0150PA', 'FINTEC GLOBAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FINTEC-PA', 'migration_from_screener'),
('0089.KL', '0089', 'TEX CYCLE TECHNOLOGY (M) BHD', 'SHARIAH', NULL, 'MYR', true, true, 'TEXCYCL', 'migration_from_screener'),
('0145.KL', '0145', 'TFP SOLUTIONS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'TFP', 'migration_from_screener'),
('0070.KL', '0070', 'MQ TECHNOLOGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MQTECH', 'migration_from_screener'),
('0198.KL', '0198', 'GDB HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GDB', 'migration_from_screener'),
('0237.KL', '0237', 'HAILY GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HAILY', 'migration_from_screener'),
('0192.KL', '0192', 'INTA BINA GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'INTA', 'migration_from_screener'),
('0058.KL', '0058', 'JCBNEXT BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'JCBNEXT', 'migration_from_screener'),
('0146.KL', '0146', 'JF TECHNOLOGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'JFTECH', 'migration_from_screener'),
('0066.KL', '0066', 'VSOLAR GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'VSOLAR', 'migration_from_screener'),
('0102.KL', '0102', 'WAJA KONSORTIUM BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'WAJA', 'migration_from_screener'),
('0197.KL', '0197', 'WEGMANS HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'WEGMANS', 'migration_from_screener'),
('0271.KL', '0271', 'WELLSPIRE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'WELLS', 'migration_from_screener'),
('0298.KL', '0298', 'WENTEL ENGINEERING HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'WENTEL', 'migration_from_screener'),
('0162.KL', '0162', 'WIDAD GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'WIDAD', 'migration_from_screener'),
('0208.KL', '0208', 'GREATECH TECHNOLOGY BERHAD', 'UNKNOWN', NULL, 'MYR', true, true, 'GREATEC', 'migration_from_screener'),
('0138.KL', '0138', 'ZETRIX AI BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ZETRIX', 'migration_from_screener'),
('0006.KL', '0006', 'PINEAPPLE RESOURCES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'PINEAPP', 'migration_from_screener'),
('0171.KL', '0171', 'PETERLABS HOLDINGS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'PLABS', 'migration_from_screener'),
('0289.KL', '0289', 'PLYTEC HOLDING BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PLYTEC', 'migration_from_screener'),
('0037.KL', '0037', 'RGB INTERNATIONAL BHD', 'SHARIAH', NULL, 'MYR', true, true, 'RGB', 'migration_from_screener'),
('03052.KL', '03052', 'RAY GO SOLAR HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'RGS', 'migration_from_screener'),
('0202.KL', '0202', 'RADIANT GLOBALTECH BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'RGTECH', 'migration_from_screener'),
('0143.KL', '0143', 'KEY ASIC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'KEYASIC', 'migration_from_screener'),
('0147.KL', '0147', 'INNITY CORPORATION BHD', 'SHARIAH', NULL, 'MYR', true, true, 'INNITY', 'migration_from_screener'),
('0154.KL', '0154', 'EA HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EAH', 'migration_from_screener'),
('0267.KL', '0267', 'ECA INTEGRATED SOLUTION BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ECA', 'migration_from_screener'),
('0059.KL', '0059', 'ECOBUILT HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ECOHLDS', 'migration_from_screener'),
('0239.KL', '0239', 'ECOMATE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ECOMATE', 'migration_from_screener'),
('0068.KL', '0068', 'ASDION BHD', 'SHARIAH', NULL, 'MYR', true, true, 'ASDION', 'migration_from_screener'),
('0105.KL', '0105', 'ASIA POLY HOLDINGS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'ASIAPLY', 'migration_from_screener'),
('03032.KL', '03032', 'ASTRAMINA GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ASTRA', 'migration_from_screener'),
('0136.KL', '0136', 'GREENYIELD BHD', 'SHARIAH', NULL, 'MYR', true, true, 'GREENYB', 'migration_from_screener'),
('0064.KL', '0064', 'EFFICIENT E-SOLUTIONS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'EFFICEN', 'migration_from_screener'),
('0065.KL', '0065', 'EXCEL FORCE MSC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'EFORCE', 'migration_from_screener'),
('0227.KL', '0227', 'ECONFRAME BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EFRAME', 'migration_from_screener'),
('0255.KL', '0255', 'ECOSCIENCE INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EIB', 'migration_from_screener'),
('0296.KL', '0296', 'HE GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HEGROUP', 'migration_from_screener'),
('0035.KL', '0035', 'HEXTAR CAPITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HEXCAP', 'migration_from_screener'),
('0072.KL', '0072', 'ERDASAN GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ERDASAN', 'migration_from_screener'),
('0190.KL', '0190', 'EVERSAFE RUBBER BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ESAFE', 'migration_from_screener'),
('0100.KL', '0100', 'ES CERAMICS TECHNOLOGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'ESCERAM', 'migration_from_screener'),
('0168.KL', '0168', 'BM GREENTECH BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BMGREEN', 'migration_from_screener'),
('0018.KL', '0018', 'LAMBO GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'LAMBO', 'migration_from_screener'),
('03053.KL', '03053', 'CC INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CCIB', 'migration_from_screener'),
('0238.KL', '0238', 'CEKD BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CEKD', 'migration_from_screener'),
('0243.KL', '0243', 'CENGILD MEDICAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CENGILD', 'migration_from_screener'),
('03024.KL', '03024', 'CE TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CETECH', 'migration_from_screener'),
('0291.KL', '0291', 'CRITICAL HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CHB', 'migration_from_screener'),
('0060.KL', '0060', 'HARVEST MIRACLE CAPITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HM', 'migration_from_screener'),
('0023.KL', '0023', 'IFCA MSC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'IFCAMSC', 'migration_from_screener'),
('0231.KL', '0231', 'FLEXIDYNAMIC HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FLEXI', 'migration_from_screener'),
('0116.KL', '0116', 'FOCUS DYNAMICS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FOCUS', 'migration_from_screener'),
('0116PA.KL', '0116PA', 'FOCUS DYNAMICS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FOCUS-PA', 'migration_from_screener'),
('0157.KL', '0157', 'FOCUS POINT HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FOCUSP', 'migration_from_screener'),
('0304.KL', '0304', 'FARM PRICE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FPHB', 'migration_from_screener'),
('0078.KL', '0078', 'GDEX BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GDEX', 'migration_from_screener'),
('0104.KL', '0104', 'GENETEC TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GENETEC', 'migration_from_screener'),
('0127.KL', '0127', 'JHM CONSOLIDATION BHD', 'SHARIAH', NULL, 'MYR', true, true, 'JHM', 'migration_from_screener'),
('03040.KL', '03040', 'JISHAN BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'JISHAN', 'migration_from_screener'),
('0285.KL', '0285', 'MERCURY SECURITIES GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MERSEC', 'migration_from_screener'),
('0207.KL', '0207', 'MESTRON HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MESTRON', 'migration_from_screener'),
('03015.KL', '03015', 'MANFORCE GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MFGROUP', 'migration_from_screener'),
('0155.KL', '0155', 'MSIAN GENOMICS RES CENTRE BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MGRC', 'migration_from_screener'),
('0126.KL', '0126', 'MICROLINK SOLUTIONS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MICROLN', 'migration_from_screener'),
('0177.KL', '0177', 'MIDTOWN GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MIDTOWN', 'migration_from_screener'),
('0112.KL', '0112', 'MIKRO MSC BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MIKROMB', 'migration_from_screener'),
('0288.KL', '0288', 'MINOX INTERNATIONAL GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MINOX', 'migration_from_screener'),
('0218.KL', '0218', 'ACO GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ACO', 'migration_from_screener'),
('0276.KL', '0276', 'AUTOCOUNT DOTCOM BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ADB', 'migration_from_screener'),
('0161.KL', '0161', 'HEXTAR INDUSTRIES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HEXIND', 'migration_from_screener'),
('0160.KL', '0160', 'HIAP HUAT HOLDINGS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'HHHCORP', 'migration_from_screener'),
('0175.KL', '0175', 'HHRG BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HHRG', 'migration_from_screener'),
('0039.KL', '0039', 'GFM SERVICES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GFM', 'migration_from_screener'),
('0029.KL', '0029', 'DIGISTAR CORPORATION BHD', 'SHARIAH', NULL, 'MYR', true, true, 'DIGISTA', 'migration_from_screener'),
('0181.KL', '0181', 'AEMULUS HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AEMULUS', 'migration_from_screener'),
('0212.KL', '0212', 'SDS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SDS', 'migration_from_screener'),
('0284.KL', '0284', 'GLOSTREXT BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GLXT', 'migration_from_screener'),
('0205.KL', '0205', 'DPI HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DPIH', 'migration_from_screener'),
('0258.KL', '0258', 'AGMO HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AGMO', 'migration_from_screener'),
('0299.KL', '0299', 'AGX GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AGX', 'migration_from_screener'),
('0122.KL', '0122', 'ADVANCE INFORMATION MARKETING', 'SHARIAH', NULL, 'MYR', true, true, 'AIM', 'migration_from_screener'),
('0209.KL', '0209', 'AIMFLEX BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AIMFLEX', 'migration_from_screener'),
('0303.KL', '0303', 'ALPHA IVF GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ALPHA', 'migration_from_screener'),
('0079.KL', '0079', 'ALDRICH RESOURCES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ALRICH', 'migration_from_screener'),
('03011.KL', '03011', 'AMLEX HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AMLEX', 'migration_from_screener'),
('03055.KL', '03055', 'DSR TAIKO BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DSR', 'migration_from_screener'),
('0269.KL', '0269', 'DS SIGMA HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DSS', 'migration_from_screener'),
('0178.KL', '0178', 'SEDANIA INNOVATOR BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SEDANIA', 'migration_from_screener'),
('03046.KL', '03046', 'DYNAFRONT HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DYNAFNT', 'migration_from_screener'),
('03058.KL', '03058', 'TOTAL DYNAMIC HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DYNAMIC', 'migration_from_screener'),
('0048.KL', '0048', 'ANCOM LOGISTICS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ANCOMLB', 'migration_from_screener'),
('0226.KL', '0226', 'ANEKA JARINGAN HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ANEKA', 'migration_from_screener'),
('03051.KL', '03051', 'ALPHA OCEAN RESOURCES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AORB', 'migration_from_screener'),
('0265.KL', '0265', 'INFOMINA BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'INFOM', 'migration_from_screener'),
('0253.KL', '0253', 'INFOLINE TEC GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'INFOTEC', 'migration_from_screener'),
('0119.KL', '0119', 'APPASIA BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'APPASIA', 'migration_from_screener'),
('0038.KL', '0038', 'ARTRONIQ BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ARTRONIQ', 'migration_from_screener'),
('0074.KL', '0074', 'GREEN OCEAN CORPORATION BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GOCEAN', 'migration_from_screener'),
('03028.KL', '03028', 'GO INNOVATE ASIA BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GOINNO', 'migration_from_screener'),
('0082.KL', '0082', 'GREEN PACKET BHD', 'SHARIAH', NULL, 'MYR', true, true, 'GPACKET', 'migration_from_screener'),
('03029.KL', '03029', 'GPP RESOURCES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'GPP', 'migration_from_screener'),
('0084.KL', '0084', 'FAST ENERGY HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'FAST', 'migration_from_screener'),
('03009.KL', '03009', 'SEERS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SEERS', 'migration_from_screener'),
('0098.KL', '0098', 'AUMAS RESOURCES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AUMAS', 'migration_from_screener'),
('03037.KL', '03037', 'AURORA ITALIA INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AURORA', 'migration_from_screener'),
('03059.KL', '03059', 'AUTORIS GROUP HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'AUTORIS', 'migration_from_screener'),
('0056.KL', '0056', 'NCT ALLIANCE BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NCT', 'migration_from_screener'),
('0235.KL', '0235', 'NESTCON BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NESTCON', 'migration_from_screener'),
('0292.KL', '0292', 'JATI TINGGI GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'JTGROUP', 'migration_from_screener'),
('03012.KL', '03012', 'BABA ECO GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BABA', 'migration_from_screener'),
('0185.KL', '0185', 'HSS ENGINEERS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HSSEB', 'migration_from_screener'),
('0278.KL', '0278', 'EDELTEQ HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EDELTEQ', 'migration_from_screener'),
('0187.KL', '0187', 'BCM ALLIANCE BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BCMALL', 'migration_from_screener'),
('0263.KL', '0263', 'BETAMEK BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BETA', 'migration_from_screener'),
('0195.KL', '0195', 'BINASAT COMMUNICATIONS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BINACOM', 'migration_from_screener'),
('0179.KL', '0179', 'BIOALPHA HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BIOHLDG', 'migration_from_screener'),
('0179PA.KL', '0179PA', 'BIOALPHA HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BIOHLDG-PA', 'migration_from_screener'),
('0020.KL', '0020', 'NETX HOLDINGS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'NETX', 'migration_from_screener'),
('0107.KL', '0107', 'EDUSPEC HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EDUSPEC', 'migration_from_screener'),
('03002.KL', '03002', 'JAGASOLUTION BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'JAGAAPP', 'migration_from_screener'),
('0002.KL', '0002', 'KOTRA INDUSTRIES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'KOTRA', 'migration_from_screener'),
('0085.KL', '0085', 'MLABS SYSTEMS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MLAB', 'migration_from_screener'),
('0034.KL', '0034', 'MMAG HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MMAG', 'migration_from_screener'),
('03027.KL', '03027', 'MMIS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MMIS', 'migration_from_screener'),
('0159.KL', '0159', 'MMM GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MMM', 'migration_from_screener'),
('0113.KL', '0113', 'MMS VENTURES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MMSV', 'migration_from_screener'),
('0103.KL', '0103', 'M N C WIRELESS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MNC', 'migration_from_screener'),
('0103PA.KL', '0103PA', 'M N C WIRELESS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MNC-PA', 'migration_from_screener'),
('0245.KL', '0245', 'MN HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MNHLDG', 'migration_from_screener'),
('03031.KL', '03031', 'POLYDAMIC GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'POLYDM', 'migration_from_screener'),
('0123.KL', '0123', 'PRIVASIA TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PRIVA', 'migration_from_screener'),
('0186.KL', '0186', 'PERAK TRANSIT BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PTRANS', 'migration_from_screener'),
('0260.KL', '0260', 'PT RESOURCES HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PTRB', 'migration_from_screener'),
('0007.KL', '0007', 'PUC BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PUC', 'migration_from_screener'),
('0217.KL', '0217', 'POWERWELL HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PWRWELL', 'migration_from_screener'),
('0196.KL', '0196', 'QES GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'QES', 'migration_from_screener'),
('0236.KL', '0236', 'RAMSSOL GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'RAMSSOL', 'migration_from_screener'),
('0010.KL', '0010', 'IRIS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'IRIS', 'migration_from_screener'),
('0111.KL', '0111', 'K-ONE TECHNOLOGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'K1', 'migration_from_screener'),
('0151.KL', '0151', 'KELINGTON GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KGB', 'migration_from_screener'),
('03030.KL', '03030', 'IDB TECHNOLOGIES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'IDBTECH', 'migration_from_screener'),
('0188.KL', '0188', 'HLT GLOBAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HLT', 'migration_from_screener'),
('0090.KL', '0090', 'ELSOFT RESEARCH BHD', 'SHARIAH', NULL, 'MYR', true, true, 'ELSOFT', 'migration_from_screener'),
('0286.KL', '0286', 'EVERGREEN MAX CASH CAPITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EMCC', 'migration_from_screener'),
('03025.KL', '03025', 'ENEST GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ENEST', 'migration_from_screener'),
('0032.KL', '0032', 'REDTONE DIGITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'REDTONE', 'migration_from_screener'),
('0081.KL', '0081', 'REKATECH CAPITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'REKATECH', 'migration_from_screener'),
('0200.KL', '0200', 'REVENUE GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'REVENUE', 'migration_from_screener'),
('0128.KL', '0128', 'FRONTKEN CORPORATION BHD', 'SHARIAH', NULL, 'MYR', true, true, 'FRONTKN', 'migration_from_screener'),
('0051.KL', '0051', 'CUSCAPI BHD', 'SHARIAH', NULL, 'MYR', true, true, 'CUSCAPI', 'migration_from_screener'),
('0219.KL', '0219', 'RESERVOIR LINK ENERGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'RL', 'migration_from_screener'),
('03036.KL', '03036', 'REDPLANET BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'RPLANET', 'migration_from_screener'),
('03039.KL', '03039', 'RTS TECHNOLOGY HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'RTSTECH', 'migration_from_screener'),
('03056.KL', '03056', 'SAFETYWARE GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SAFETY', 'migration_from_screener'),
('0183.KL', '0183', 'SALUTICA BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SALUTE', 'migration_from_screener'),
('0223.KL', '0223', 'SAMAIDEN GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SAMAIDEN', 'migration_from_screener'),
('03057.KL', '03057', 'SANCY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SANCY', 'migration_from_screener'),
('0133.KL', '0133', 'SANICHI TECHNOLOGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SANICHI', 'migration_from_screener'),
('0300.KL', '0300', 'SBH MARINE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SBH', 'migration_from_screener'),
('0109.KL', '0109', 'SC ESTATE BUILDER BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SCBUILD', 'migration_from_screener'),
('0158.KL', '0158', 'SCC HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SCC', 'migration_from_screener'),
('0225.KL', '0225', 'SOUTHERN CABLE GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SCGBHD', 'migration_from_screener'),
('0099.KL', '0099', 'SCICOM (MSC) BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SCICOM', 'migration_from_screener'),
('0001.KL', '0001', 'SUPERCOMNET TECHNOLOGIES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SCOMNET', 'migration_from_screener'),
('0028.KL', '0028', 'SCOPE INDUSTRIES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SCOPE', 'migration_from_screener'),
('0011.KL', '0011', 'BRITE-TECH BHD', 'SHARIAH', NULL, 'MYR', true, true, 'BTECH', 'migration_from_screener'),
('03042.KL', '03042', 'BV LAND HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'BVLH', 'migration_from_screener'),
('0191.KL', '0191', 'CABNET HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CABNET', 'migration_from_screener'),
('0041.KL', '0041', 'HONG SENG CONSOLIDATED BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HONGSENG', 'migration_from_screener'),
('03060.KL', '03060', 'HYDROPIPES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HPI', 'migration_from_screener'),
('03021.KL', '03021', 'EQUITIESTRACKER HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ETH', 'migration_from_screener'),
('0163.KL', '0163', 'CAREPLUS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CAREPLS', 'migration_from_screener'),
('0228.KL', '0228', 'HPP HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'HPPHB', 'migration_from_screener'),
('0131.KL', '0131', 'DIVFEX BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DFX', 'migration_from_screener'),
('0293.KL', '0293', 'KJTS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KJTS', 'migration_from_screener'),
('0170.KL', '0170', 'KANGER INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KANGER', 'migration_from_screener'),
('0174.KL', '0174', 'EVD BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EVD', 'migration_from_screener'),
('0174PA.KL', '0174PA', 'EVD BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'EVD-PA', 'migration_from_screener'),
('0173.KL', '0173', 'CATCHA DIGITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'CATCHA', 'migration_from_screener'),
('0054.KL', '0054', 'KARYON INDUSTRIES BHD', 'SHARIAH', NULL, 'MYR', true, true, 'KARYON', 'migration_from_screener'),
('0282.KL', '0282', 'KGW GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KGW', 'migration_from_screener'),
('0210.KL', '0210', 'KIM HIN JOO (MALAYSIA) BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KHJB', 'migration_from_screener'),
('0024.KL', '0024', 'JAG BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'JAG', 'migration_from_screener'),
('0306.KL', '0306', 'SMART ASIA CHEMICAL BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SMART', 'migration_from_screener'),
('0203.KL', '0203', 'SECUREMETRIC BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SMETRIC', 'migration_from_screener'),
('03023.KL', '03023', 'SMILE-LINK HEALTHCARE GLOBAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SMILE', 'migration_from_screener'),
('0108.KL', '0108', 'N2N CONNECT BHD', 'SHARIAH', NULL, 'MYR', true, true, 'N2N', 'migration_from_screener'),
('0117.KL', '0117', 'SMRT HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SMRT', 'migration_from_screener'),
('0169.KL', '0169', 'SMTRACK BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SMTRACK', 'migration_from_screener'),
('03054.KL', '03054', 'SNOWFIT GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SNOWFIT', 'migration_from_screener'),
('0259.KL', '0259', 'SNS NETWORK TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SNS', 'migration_from_screener'),
('03041.KL', '03041', 'ONETECH SOLUTIONS HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, '1TECH', 'migration_from_screener'),
('0012.KL', '0012', 'THREE-A RESOURCES BHD', 'SHARIAH', NULL, 'MYR', true, true, '3A', 'migration_from_screener'),
('0093.KL', '0093', 'SOLUTION GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SOLUTN', 'migration_from_screener'),
('0216.KL', '0216', 'SPRING ART HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SPRING', 'migration_from_screener'),
('0129.KL', '0129', 'SILVER RIDGE HOLDINGS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SRIDGE', 'migration_from_screener'),
('0045.KL', '0045', 'SOUTHERN SCORE BUILDERS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SSB8', 'migration_from_screener'),
('0287.KL', '0287', 'SSF HOME GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SSF', 'migration_from_screener'),
('0080.KL', '0080', 'STRAITS ENERGY RESOURCES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'STRAITS', 'migration_from_screener'),
('03050.KL', '03050', 'SUNMOW HOLDING BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SUNMOW', 'migration_from_screener'),
('030501.KL', '030501', 'SUNMOW HOLDING BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SUNMOW-PA', 'migration_from_screener'),
('0262.KL', '0262', 'SUNVIEW GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SUNVIEW', 'migration_from_screener'),
('0148.KL', '0148', 'SUNZEN GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SUNZEN', 'migration_from_screener'),
('0279.KL', '0279', 'SYNERGY HOUSE BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'SYNERGY', 'migration_from_screener'),
('0050.KL', '0050', 'SYSTECH BHD', 'SHARIAH', NULL, 'MYR', true, true, 'SYSTECH', 'migration_from_screener'),
('0241.KL', '0241', 'TAGHILL HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TAGHILL', 'migration_from_screener'),
('0211.KL', '0211', 'TASHIN HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TASHIN', 'migration_from_screener'),
('0221.KL', '0221', 'TCS GROUP HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TCS', 'migration_from_screener'),
('0230.KL', '0230', 'TELADAN GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TELADAN', 'migration_from_screener'),
('0280.KL', '0280', 'MYMBN BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MBN', 'migration_from_screener'),
('0167.KL', '0167', 'MCLEAN TECHNOLOGIES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MCLEAN', 'migration_from_screener'),
('03022.KL', '03022', 'MCOM HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MCOM', 'migration_from_screener'),
('0193.KL', '0193', 'KINERGY ADVANCEMENT BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KINERGY', 'migration_from_screener'),
('0176.KL', '0176', 'KRONOLOGI ASIA BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KRONO', 'migration_from_screener'),
('0180.KL', '0180', 'KIM TECK CHEONG CONSOLIDATED BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KTC', 'migration_from_screener'),
('0268.KL', '0268', 'L&P GLOBAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'L&PBHD', 'migration_from_screener'),
('0266.KL', '0266', 'LEFORM BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'LEFORM', 'migration_from_screener'),
('0249.KL', '0249', 'LGMS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'LGMS', 'migration_from_screener'),
('0182.KL', '0182', 'LKL INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'LKL', 'migration_from_screener'),
('0075.KL', '0075', 'LYC HEALTHCARE BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'LYC', 'migration_from_screener'),
('0095.KL', '0095', 'MAG HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MAG', 'migration_from_screener'),
('0189.KL', '0189', 'MATANG BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MATANG', 'migration_from_screener'),
('0302.KL', '0302', 'TOPMIX BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TOPMIX', 'migration_from_screener'),
('0199.KL', '0199', 'TRI-MODE SYSTEM (M) BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TRIMODE', 'migration_from_screener'),
('0118.KL', '0118', 'TRIVE PROPERTY GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TRIVE', 'migration_from_screener'),
('0297.KL', '0297', 'TSA GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TSA', 'migration_from_screener'),
('0272.KL', '0272', 'TT VISION HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'TTVHB', 'migration_from_screener'),
('0005.KL', '0005', 'UCREST BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'UCREST', 'migration_from_screener'),
('0256.KL', '0256', 'UMEDIC GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'UMC', 'migration_from_screener'),
('0257.KL', '0257', 'UNIQUE FIRE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'UNIQUE', 'migration_from_screener'),
('0247.KL', '0247', 'UNITRADE INDUSTRIES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'UNITRAD', 'migration_from_screener'),
('03017.KL', '03017', 'UNI WALL APS HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'UNIWALL', 'migration_from_screener'),
('03043.KL', '03043', 'UCI RESOURCES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'UTAMA', 'migration_from_screener'),
('0069.KL', '0069', 'VINVEST CAPITAL HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'VINVEST', 'migration_from_screener'),
('0120.KL', '0120', 'VISDYNAMICS HOLDINGS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'VIS', 'migration_from_screener'),
('0273.KL', '0273', 'VESTLAND BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'VLB', 'migration_from_screener'),
('0232.KL', '0232', 'VOLCANO BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'VOLCANO', 'migration_from_screener'),
('0096.KL', '0096', 'NEXGRAM HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NEXGRAM', 'migration_from_screener'),
('0083.KL', '0083', 'NOTION VTEC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'NOTION', 'migration_from_screener'),
('0201.KL', '0201', 'NOVA WELLNESS GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NOVA', 'migration_from_screener'),
('0026.KL', '0026', 'NOVA MSC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'NOVAMSC', 'migration_from_screener'),
('0017.KL', '0017', 'NOVA TECHNOLOGY SERVICES BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NOVATECH', 'migration_from_screener'),
('03045.KL', '03045', 'NOVELPLUS TECHNOLOGY BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NP', 'migration_from_screener'),
('03006.KL', '03006', 'NOVA PHARMA SOLUTIONS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NPS', 'migration_from_screener'),
('0172.KL', '0172', 'OCK GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'OCK', 'migration_from_screener'),
('0049.KL', '0049', 'OCEANCASH PACIFIC BHD', 'SHARIAH', NULL, 'MYR', true, true, 'OCNCASH', 'migration_from_screener'),
('0106.KL', '0106', 'OPENMOVE AI BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'OMAI', 'migration_from_screener'),
('0040.KL', '0040', 'OPENSYS (M) BHD', 'SHARIAH', NULL, 'MYR', true, true, 'OPENSYS', 'migration_from_screener'),
('0275.KL', '0275', 'OPPSTAR BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'OPPSTAR', 'migration_from_screener'),
('0222.KL', '0222', 'OPTIMAX HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'OPTIMAX', 'migration_from_screener'),
('0252.KL', '0252', 'ORGABIO HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ORGABIO', 'migration_from_screener'),
('0053.KL', '0053', 'OSK VENTURES INTERNATIONAL BHD', 'SHARIAH', NULL, 'MYR', true, true, 'OSKVI', 'migration_from_screener'),
('0153.KL', '0153', 'OVERSEA ENTERPRISE BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'OVERSEA', 'migration_from_screener'),
('0220.KL', '0220', 'OCEAN VANTAGE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'OVH', 'migration_from_screener'),
('0290.KL', '0290', 'PANDA ECO SYSTEM BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PANDA', 'migration_from_screener'),
('0140.KL', '0140', 'XOX NETWORKS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'XOXNET', 'migration_from_screener'),
('0025.KL', '0025', 'YBS INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'YBS', 'migration_from_screener'),
('0248.KL', '0248', 'YEW LEE PACIFIC GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'YEWLEE', 'migration_from_screener'),
('0086.KL', '0086', 'YGL CONVERGENCE BHD', 'SHARIAH', NULL, 'MYR', true, true, 'YGL', 'migration_from_screener'),
('0250.KL', '0250', 'YX PRECIOUS METALS BHD', 'SHARIAH', NULL, 'MYR', true, true, 'YXPM', 'migration_from_screener'),
('0301.KL', '0301', 'ZANTAT HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ZANTAT', 'migration_from_screener'),
('0094.KL', '0094', 'ZEN TECH INTERNATIONAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'ZENTECH', 'migration_from_screener'),
('0036.KL', '0036', 'KEY ALLIANCE GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'KGROUP', 'migration_from_screener'),
('0281.KL', '0281', 'DAYTHREE DIGITAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DAY3', 'migration_from_screener'),
('0283.KL', '0283', 'DC HEALTHCARE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DCHCARE', 'migration_from_screener'),
('0152.KL', '0152', 'DGB ASIA BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'DGB', 'migration_from_screener'),
('0213.KL', '0213', 'MTAG GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MTAG', 'migration_from_screener'),
('0295.KL', '0295', 'MASTER TEC GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'MTEC', 'migration_from_screener'),
('0092.KL', '0092', 'MTOUCHE TECHNOLOGY BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MTOUCHE', 'migration_from_screener'),
('0043.KL', '0043', 'METRONIC GLOBAL BHD', 'SHARIAH', NULL, 'MYR', true, true, 'MTRONIC', 'migration_from_screener'),
('0206.KL', '0206', 'GAGASAN NADI CERGAS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NADIBHD', 'migration_from_screener'),
('0270.KL', '0270', 'NATIONGATE HOLDINGS BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'NATGATE', 'migration_from_screener'),
('0022.KL', '0022', 'PARLO BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PARLO', 'migration_from_screener'),
('0233.KL', '0233', 'PEKAT GROUP BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PEKAT', 'migration_from_screener'),
('0091.KL', '0091', 'PROPEL GLOBAL BERHAD', 'SHARIAH', NULL, 'MYR', true, true, 'PGB', 'migration_from_screener') ON CONFLICT (ticker_full) DO UPDATE SET is_top300 = true, market = 'MYR', updated_at = now();