-- Enable UUID extension just in case, though not strictly needed unless IDs use UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1) klse_stocks
CREATE TABLE IF NOT EXISTS public.klse_stocks (
    ticker_full TEXT PRIMARY KEY, -- e.g. "1155.KL"
    ticker_code TEXT NOT NULL,    -- e.g. "1155"
    company_name TEXT NOT NULL,
    shariah_status TEXT DEFAULT 'SHARIAH', -- "SHARIAH", "NON_SHARIAH"
    sector TEXT,
    market TEXT, -- "Main", "Ace", etc.
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for searching/filtering
CREATE INDEX IF NOT EXISTS idx_klse_stocks_shariah ON public.klse_stocks(shariah_status);
CREATE INDEX IF NOT EXISTS idx_klse_stocks_active ON public.klse_stocks(is_active);


-- 2) klse_prices_daily
CREATE TABLE IF NOT EXISTS public.klse_prices_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_full TEXT NOT NULL REFERENCES public.klse_stocks(ticker_full) ON DELETE CASCADE,
    price_date DATE NOT NULL,
    close DECIMAL(10, 4) NOT NULL, -- Handle penny stocks and high prices
    volume BIGINT,
    source VARCHAR(50) DEFAULT 'manual', -- e.g. "scraper", "manual"
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ticker_full, price_date)
);

-- Index for date range queries and joins
CREATE INDEX IF NOT EXISTS idx_prices_ticker_date ON public.klse_prices_daily(ticker_full, price_date DESC);
CREATE INDEX IF NOT EXISTS idx_prices_date ON public.klse_prices_daily(price_date);


-- 3) klse_liquidity_rank
-- Stores computed liquidity ranks (e.g. top 300 by avg volume)
CREATE TABLE IF NOT EXISTS public.klse_liquidity_rank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    as_of_date DATE NOT NULL,
    ticker_full TEXT NOT NULL REFERENCES public.klse_stocks(ticker_full) ON DELETE CASCADE,
    avg_vol_20d BIGINT,
    rank_no INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (as_of_date, ticker_full)
);

-- Index for fetching top N liquid stocks for a given date
CREATE INDEX IF NOT EXISTS idx_liquidity_date_rank ON public.klse_liquidity_rank(as_of_date, rank_no);


-- 4) sync_jobs
-- Tracks the status of EOD sync operations
CREATE TABLE IF NOT EXISTS public.sync_jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    as_of_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued', -- "queued", "running", "done", "failed"
    total_tickers INTEGER DEFAULT 0,
    processed_count INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sync_jobs_date ON public.sync_jobs(as_of_date DESC);


-- 5) sync_logs
-- Detailed logs for debugging sync issues per ticker
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID REFERENCES public.sync_jobs(id) ON DELETE CASCADE,
    ticker_full TEXT,
    status TEXT, -- "success", "error"
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sync_logs_job ON public.sync_logs(job_id);


-- 6) screener_results_cache
-- Caches the computed screener results to avoid re-calculating on every page load
CREATE TABLE IF NOT EXISTS public.screener_results_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    as_of_date DATE NOT NULL,
    universe TEXT DEFAULT 'shariah_top300', -- e.g. "shariah_top300", "all"
    min_score DECIMAL(4, 2) DEFAULT 0,
    results_json JSONB, -- The full array of screener results
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_screener_cache_date_universe ON public.screener_results_cache(as_of_date DESC, universe);

-- RLS Policies (Row Level Security)
-- Allow public (anon) read access to specific tables if needed, otherwise restrict to service_role mostly.
-- For this app, frontend reads screener_results_cache and possibly stocks/prices.
-- Writing is restricted to service_role (backend functions).

ALTER TABLE public.klse_stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.klse_prices_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.klse_liquidity_rank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screener_results_cache ENABLE ROW LEVEL SECURITY;

-- Read policies for anon (public)
CREATE POLICY "Allow public read on stocks" ON public.klse_stocks FOR SELECT USING (true);
CREATE POLICY "Allow public read on prices" ON public.klse_prices_daily FOR SELECT USING (true);
CREATE POLICY "Allow public read on liquidity" ON public.klse_liquidity_rank FOR SELECT USING (true);
CREATE POLICY "Allow public read on sync_jobs" ON public.sync_jobs FOR SELECT USING (true);
CREATE POLICY "Allow public read on screener_cache" ON public.screener_results_cache FOR SELECT USING (true);

-- Write policies (service_role only - implicit by default if no policy grants write, but being explicit is good practice or just rely on service_role bypassing RLS)
-- We do not create write policies for anon. Only service_role will write.

